### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by Aslemammad** [deref/uni#4]
I'm really chuffed about this repo. Currently, I'm learning golang and wanted to contribute to uni to expand my knowledge and help that amazing repo. Are there any guidelines and requirements to contribute?

**Comment by brandonbloom** [comment]
Pretty early days for this project, but happy to have contributors. Glad you're excited.

I don't have any low-hanging fruit or contributing guidelines or anything. If you've got something in mind, feel free to file an issue or a (empty even) draft PR to start a discussion.

**Comment by Aslemammad** [comment]
Thanks, I would be happy to have a better (more specific) roadmap/problems to solve; I'd love to help.
BTW do you have discord? So I can ask some questions or give me some tasks to do/solve on this project?

**Comment by brandonbloom** [comment]
There's some stuff in the doc directory: https://github.com/brandonbloom/uni/tree/main/doc

Otherwise, no, no community or discord or anything around this yet.

**Comment by Aslemammad** [comment]
Let me check them and start, thanks.

**Comment by brandonbloom** [comment]
Hi @Aslemammad, I've setup Github Discussions over at https://github.com/deref/uni/discussions – please start a thread over there if you'd like to further discuss ways to contribute. Thanks!
